const challenges = [
  { title: "Turn off lights when leaving a room", subtitle: "turnofflight", carbonReduction: 0.2, points: 5 },
  { title: "Unplug devices when not in use", subtitle: "unplugdevice", carbonReduction: 0.5, points: 7 },
  { title: "Use public transport once a week", subtitle: "publictransport", carbonReduction: 2.5, points: 10 },
  { title: "Carpool to work or school", subtitle: "carpool", carbonReduction: 1.5, points: 8 },
  { title: "Go meatless one day a week", subtitle: "meatlessday", carbonReduction: 3.0, points: 10 },
  { title: "Reduce shower time by 2 minutes", subtitle: "shortenshower", carbonReduction: 0.1, points: 5 },
  { title: "Switch to LED lights", subtitle: "ledlights", carbonReduction: 0.3, points: 6 },
  { title: "Use reusable shopping bags", subtitle: "reusablebags", carbonReduction: 0.02, points: 3 },
  { title: "Wash clothes in cold water", subtitle: "coldwaterwash", carbonReduction: 0.4, points: 5 },
  { title: "Limit heating/air conditioning use", subtitle: "limithvac", carbonReduction: 1.0, points: 7 },
  { title: "Buy local produce", subtitle: "localproduce", carbonReduction: 0.3, points: 4 },
  { title: "Opt for digital receipts", subtitle: "digitalreceipts", carbonReduction: 0.01, points: 2 },
  { title: "Avoid single-use plastics", subtitle: "singleuseplastics", carbonReduction: 0.05, points: 3 },
  { title: "Conduct a home energy audit", subtitle: "energyaudit", carbonReduction: 0.2, points: 5 },
  { title: "Lower your thermostat in winter", subtitle: "lowerthermostat", carbonReduction: 0.8, points: 6 },
  { title: "Dry clothes on a clothesline", subtitle: "clothesline", carbonReduction: 0.5, points: 6 },
  { title: "Bike instead of drive for short trips", subtitle: "biketoinstead", carbonReduction: 1.0, points: 8 },
  { title: "Plant a tree or shrub", subtitle: "plantatree", carbonReduction: 15.0, points: 20 },
  { title: "Cook with a lid on pots and pans", subtitle: "cookwithlid", carbonReduction: 0.2, points: 3 },
  { title: "Switch to a low-flow showerhead", subtitle: "lowflowshower", carbonReduction: 0.3, points: 6 },
  { title: "Use reusable water bottles", subtitle: "reusablebottle", carbonReduction: 0.1, points: 3 },
  { title: "Reduce paper towel usage", subtitle: "reducepapertowel", carbonReduction: 0.1, points: 4 },
  { title: "Compost food scraps", subtitle: "compost", carbonReduction: 0.3, points: 5 },
  { title: "Bring your own coffee mug", subtitle: "reusablemug", carbonReduction: 0.05, points: 3 },
  { title: "Take shorter showers", subtitle: "shortershower", carbonReduction: 0.1, points: 5 },
  { title: "Buy products with minimal packaging", subtitle: "minimalpackaging", carbonReduction: 0.05, points: 3 },
  { title: "Replace air filters in HVAC systems", subtitle: "replacehvacfilter", carbonReduction: 0.2, points: 4 },
  { title: "Use rechargeable batteries", subtitle: "rechargeablebattery", carbonReduction: 0.5, points: 5 },
  { title: "Telecommute when possible", subtitle: "telecommute", carbonReduction: 2.0, points: 10 },
  { title: "Buy energy-efficient appliances", subtitle: "energyefficientappliances", carbonReduction: 1.5, points: 8 },
  { title: "Recycle electronics properly", subtitle: "recycleelectronics", carbonReduction: 0.3, points: 5 },
  { title: "Use public bike-sharing systems", subtitle: "bikesharing", carbonReduction: 0.5, points: 4 },
  { title: "Share books instead of buying new", subtitle: "sharebooks", carbonReduction: 0.1, points: 2 },
  { title: "Donate old clothes", subtitle: "donateclothes", carbonReduction: 0.3, points: 5 },
  { title: "Avoid fast fashion", subtitle: "avoidfastfashion", carbonReduction: 0.5, points: 6 },
  { title: "Use cloth napkins instead of paper", subtitle: "clothnapkins", carbonReduction: 0.02, points: 3 },
  { title: "Grow your own herbs or vegetables", subtitle: "growyourown", carbonReduction: 0.5, points: 5 },
  { title: "Avoid products with palm oil", subtitle: "avoidpalmoil", carbonReduction: 0.1, points: 4 },
  { title: "Support renewable energy", subtitle: "renewableenergy", carbonReduction: 1.0, points: 7 },
  { title: "Use a broom instead of a vacuum", subtitle: "usebroom", carbonReduction: 0.2, points: 3 },
  { title: "Limit screen time", subtitle: "limitscreentime", carbonReduction: 0.1, points: 4 }
];

export default challenges;